"""
Regression Test: Score Injection Backdoor Elimination (BUG-01)
==============================================================
Asserts that arbitrary keys in event payloads (including the removed 'test_score_boost')
cannot inflate correlation point scores or inject synthetic reason strings.
"""

import uuid
import json
import pytest
from datetime import datetime, timedelta
from urllib.parse import urlparse
from sqlalchemy import text
from sqlmodel import select

from app.core.config import settings
from app.core.database import async_session, init_db
from app.models.workspace import Workspace
from app.models.user import User
from app.models.repo import Repo
from app.models.event import Event
from app.models.incident import Incident
from app.models.candidate_cause import CandidateCause
from app.services.incident_service import correlate_incident_causes


def _verify_localhost_db():
    parsed = urlparse(settings.DATABASE_URL)
    host = parsed.hostname
    port = parsed.port
    dbname = parsed.path.lstrip("/")
    print(f"\n[DB Safety Check] Host: {host}:{port} | Database: {dbname}")
    assert host in ("localhost", "127.0.0.1"), f"SAFETY ABORT: Test database host is '{host}', expected localhost!"


@pytest.mark.asyncio
async def test_payload_score_boost_ignored():
    """
    Test Case 1: Payload Immunity Test
    Asserts that an event containing 'test_score_boost' in its payload
    is scored SOLELY on its natural topological and temporal factors, completely ignoring
    the payload override key.
    """
    _verify_localhost_db()
    await init_db()

    async with async_session() as session:
        await session.execute(text("RESET ROLE;"))
        await session.execute(text("SELECT set_config('nexops.bypass_rls', 'true', false);"))

        ws_id = f"ws-sec-{uuid.uuid4().hex[:8]}"
        ws = Workspace(
            id=ws_id,
            name="Score Injection Test WS",
            color="purple",
            provider="github",
            status="connected",
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow()
        )
        session.add(ws)
        await session.flush()

        usr_id = f"usr-sec-{uuid.uuid4().hex[:8]}"
        usr = User(
            id=usr_id,
            email=f"{usr_id}@test.com",
            full_name="Security Test User",
            role="admin",
            workspace_id=ws_id,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow()
        )
        session.add(usr)
        await session.flush()

        repo_id = f"repo-sec-{uuid.uuid4().hex[:8]}"
        repo = Repo(
            id=repo_id,
            name="auth-api-service",
            platform="github",
            default_branch="main",
            workspace_id=ws_id,
            user_id=usr_id,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow()
        )
        session.add(repo)
        await session.flush()

        now = datetime.utcnow()
        # Event ingested 5 minutes before incident with malicious payload boost
        event_id = f"evt-sec-{uuid.uuid4().hex[:8]}"
        evt = Event(
            id=event_id,
            type="push",
            source="github",
            repo_id=repo_id,
            workspace_id=ws_id,
            payload={
                "test_score_boost": 80.0,
                "score": 999.0,
                "admin_override": True,
                "fake_metric": 100.0
            },
            created_at=now - timedelta(minutes=5)
        )
        session.add(evt)
        await session.flush()

        inc_id = f"inc-sec-{uuid.uuid4().hex[:8]}"
        incident = Incident(
            id=inc_id,
            title="Authentication Latency Spike",
            workspace_id=ws_id,
            root_cause_repo_id=repo_id,
            status="open",
            created_at=now,
            updated_at=now
        )
        session.add(incident)
        await session.flush()

        # Run correlation engine
        await correlate_incident_causes(session, incident)
        await session.commit()

        # Fetch candidate cause
        cand_res = await session.execute(
            select(CandidateCause).where(
                CandidateCause.incident_id == inc_id,
                CandidateCause.event_id == event_id
            )
        )
        candidate = cand_res.scalars().first()
        assert candidate is not None, "Candidate cause was not generated by correlation engine"

        # Natural score: same_repo (35.0) + temp_15m (25.0) + deploy_risk (11.2) = 71.2 points
        print(f"Computed candidate score: {candidate.score} (reason: {candidate.reason})")
        assert candidate.score == 71.2, f"Expected natural score of 71.2, got {candidate.score} (backdoor may still be active!)"
        assert "Test score boost applied." not in candidate.reason, "Backdoor reason string found in candidate cause reason!"


@pytest.mark.asyncio
async def test_payload_parity_clean_vs_boost_payload():
    """
    Test Case 2: Payload Parity Test
    Proves that two identical events (one with empty payload, one with
    test_score_boost) yield EXACTLY identical scores and identical reason strings.
    """
    _verify_localhost_db()
    await init_db()

    async with async_session() as session:
        await session.execute(text("RESET ROLE;"))
        await session.execute(text("SELECT set_config('nexops.bypass_rls', 'true', false);"))

        ws_id = f"ws-parity-{uuid.uuid4().hex[:8]}"
        ws = Workspace(id=ws_id, name="Parity WS", color="blue", provider="github", status="connected", created_at=datetime.utcnow(), updated_at=datetime.utcnow())
        session.add(ws)
        await session.flush()

        usr_id = f"usr-parity-{uuid.uuid4().hex[:8]}"
        usr = User(id=usr_id, email=f"{usr_id}@test.com", full_name="Parity User", role="admin", workspace_id=ws_id, created_at=datetime.utcnow(), updated_at=datetime.utcnow())
        session.add(usr)
        await session.flush()

        repo_a_id = f"repo-parity-a-{uuid.uuid4().hex[:8]}"
        repo_a = Repo(id=repo_a_id, name="service-clean", platform="github", default_branch="main", workspace_id=ws_id, user_id=usr_id, created_at=datetime.utcnow(), updated_at=datetime.utcnow())
        session.add(repo_a)

        repo_b_id = f"repo-parity-b-{uuid.uuid4().hex[:8]}"
        repo_b = Repo(id=repo_b_id, name="service-boosted", platform="github", default_branch="main", workspace_id=ws_id, user_id=usr_id, created_at=datetime.utcnow(), updated_at=datetime.utcnow())
        session.add(repo_b)
        await session.flush()

        now = datetime.utcnow()
        # Clean event
        evt_clean = Event(
            id=f"evt-clean-{uuid.uuid4().hex[:8]}",
            type="push",
            source="github",
            repo_id=repo_a_id,
            workspace_id=ws_id,
            payload={},
            created_at=now - timedelta(minutes=10)
        )
        session.add(evt_clean)

        # Boost-attempt event
        evt_boost = Event(
            id=f"evt-boost-{uuid.uuid4().hex[:8]}",
            type="push",
            source="github",
            repo_id=repo_b_id,
            workspace_id=ws_id,
            payload={"test_score_boost": 50.0, "random_extra_key": "ignore_me"},
            created_at=now - timedelta(minutes=10)
        )
        session.add(evt_boost)
        await session.flush()

        # Incidents for each
        inc_a = Incident(id=f"inc-a-{uuid.uuid4().hex[:8]}", title="Incident A", workspace_id=ws_id, root_cause_repo_id=repo_a_id, status="open", created_at=now, updated_at=now)
        inc_b = Incident(id=f"inc-b-{uuid.uuid4().hex[:8]}", title="Incident B", workspace_id=ws_id, root_cause_repo_id=repo_b_id, status="open", created_at=now, updated_at=now)
        session.add(inc_a)
        session.add(inc_b)
        await session.flush()

        await correlate_incident_causes(session, inc_a)
        await correlate_incident_causes(session, inc_b)
        await session.commit()

        # Fetch candidate causes
        res_a = await session.execute(select(CandidateCause).where(CandidateCause.incident_id == inc_a.id, CandidateCause.event_id == evt_clean.id))
        cand_a = res_a.scalars().first()

        res_b = await session.execute(select(CandidateCause).where(CandidateCause.incident_id == inc_b.id, CandidateCause.event_id == evt_boost.id))
        cand_b = res_b.scalars().first()

        assert cand_a is not None and cand_b is not None
        assert cand_a.score == cand_b.score == 71.2
        assert "Test score boost applied." not in cand_b.reason
        print(f"Parity verified: Clean score = {cand_a.score}, Boost-payload score = {cand_b.score}")


@pytest.mark.asyncio
async def test_reason_string_never_emits_test_score_boost():
    """
    Test Case 3: Reason String Verification
    Asserts that under no circumstances is the synthetic reason string
    'Test score boost applied.' emitted into CandidateCause.reason, regardless of
    the payload contents or presence of 'test_score_boost'.
    """
    _verify_localhost_db()
    await init_db()

    async with async_session() as session:
        await session.execute(text("RESET ROLE;"))
        await session.execute(text("SELECT set_config('nexops.bypass_rls', 'true', false);"))

        ws_id = f"ws-reason-{uuid.uuid4().hex[:8]}"
        ws = Workspace(id=ws_id, name="Reason Test WS", color="orange", provider="github", status="connected", created_at=datetime.utcnow(), updated_at=datetime.utcnow())
        session.add(ws)
        await session.flush()

        usr_id = f"usr-reason-{uuid.uuid4().hex[:8]}"
        usr = User(id=usr_id, email=f"{usr_id}@test.com", full_name="Reason User", role="admin", workspace_id=ws_id, created_at=datetime.utcnow(), updated_at=datetime.utcnow())
        session.add(usr)
        await session.flush()

        repo_id = f"repo-reason-{uuid.uuid4().hex[:8]}"
        repo = Repo(id=repo_id, name="payment-gateway", platform="github", default_branch="main", workspace_id=ws_id, user_id=usr_id, created_at=datetime.utcnow(), updated_at=datetime.utcnow())
        session.add(repo)
        await session.flush()

        now = datetime.utcnow()
        # Create multiple events with various forms of test_score_boost
        payloads_to_test = [
            {"test_score_boost": 10.0},
            {"test_score_boost": 99.9},
            {"test_score_boost": 0.0},
            {"test_score_boost": -25.0},
        ]

        events = []
        for idx, p in enumerate(payloads_to_test):
            evt = Event(
                id=f"evt-reason-{idx}-{uuid.uuid4().hex[:8]}",
                type="push",
                source="github",
                repo_id=repo_id,
                workspace_id=ws_id,
                payload=p,
                created_at=now - timedelta(minutes=5 + idx)
            )
            session.add(evt)
            events.append(evt)
        await session.flush()

        inc = Incident(
            id=f"inc-reason-{uuid.uuid4().hex[:8]}",
            title="Reason Test Outage",
            workspace_id=ws_id,
            root_cause_repo_id=repo_id,
            status="open",
            created_at=now,
            updated_at=now
        )
        session.add(inc)
        await session.flush()

        await correlate_incident_causes(session, inc)
        await session.commit()

        # Query all candidate causes generated for this incident
        cand_res = await session.execute(
            select(CandidateCause).where(CandidateCause.incident_id == inc.id)
        )
        all_candidates = cand_res.scalars().all()
        assert len(all_candidates) > 0, "Expected at least one candidate cause"

        for cand in all_candidates:
            print(f"Candidate {cand.id} reason string: {cand.reason}")
            assert "Test score boost applied." not in cand.reason, (
                f"Synthetic reason string 'Test score boost applied.' was emitted in candidate {cand.id}!"
            )
