"""baseline_migration

Revision ID: 1951c5a1ffce
Revises: 
Create Date: 2026-07-08 13:10:30.411852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1951c5a1ffce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('github_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('pagerduty_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pagerduty_webhook_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pagerduty_webhook_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('repos',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cluster_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_commit_at', sa.DateTime(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('open_prs', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('contributors', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Float(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('ci_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('github_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_cluster_id'), 'repos', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_repos_id'), 'repos', ['id'], unique=False)
    op.create_index(op.f('ix_repos_name'), 'repos', ['name'], unique=False)
    op.create_index(op.f('ix_repos_user_id'), 'repos', ['user_id'], unique=False)
    op.create_index(op.f('ix_repos_workspace_id'), 'repos', ['workspace_id'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_repo_id'], ['repos.id'], ),
    sa.ForeignKeyConstraint(['target_repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_id'), 'dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_dependencies_source_repo_id'), 'dependencies', ['source_repo_id'], unique=False)
    op.create_index(op.f('ix_dependencies_target_repo_id'), 'dependencies', ['target_repo_id'], unique=False)
    op.create_index(op.f('ix_dependencies_type'), 'dependencies', ['type'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deployed_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('commit_hash', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('changelog', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_basis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_environment'), 'deployments', ['environment'], unique=False)
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_index(op.f('ix_deployments_repo_id'), 'deployments', ['repo_id'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('pd_event_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('pd_incident_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_pd_incident_id'), 'events', ['pd_incident_id'], unique=False)
    op.create_index(op.f('ix_events_processed'), 'events', ['processed'], unique=False)
    op.create_index(op.f('ix_events_repo_id'), 'events', ['repo_id'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cluster_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('root_cause_repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('impacted_repos', sa.JSON(), nullable=True),
    sa.Column('impact_summary', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('pd_incident_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['root_cause_repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_cluster_id'), 'incidents', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_pd_incident_id'), 'incidents', ['pd_incident_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_repo_id'), 'alerts', ['repo_id'], unique=False)
    op.create_index(op.f('ix_alerts_resolved'), 'alerts', ['resolved'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('candidate_causes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'event_id', name='uq_candidate_cause_incident_event')
    )
    op.create_index(op.f('ix_candidate_causes_id'), 'candidate_causes', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_causes_incident_id'), 'candidate_causes', ['incident_id'], unique=False)
    op.create_index(op.f('ix_candidate_causes_repo_id'), 'candidate_causes', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_causes_repo_id'), table_name='candidate_causes')
    op.drop_index(op.f('ix_candidate_causes_incident_id'), table_name='candidate_causes')
    op.drop_index(op.f('ix_candidate_causes_id'), table_name='candidate_causes')
    op.drop_table('candidate_causes')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_repo_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_pd_incident_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_cluster_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_repo_id'), table_name='events')
    op.drop_index(op.f('ix_events_processed'), table_name='events')
    op.drop_index(op.f('ix_events_pd_incident_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_repo_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_environment'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_dependencies_type'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_target_repo_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_source_repo_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_repos_workspace_id'), table_name='repos')
    op.drop_index(op.f('ix_repos_user_id'), table_name='repos')
    op.drop_index(op.f('ix_repos_name'), table_name='repos')
    op.drop_index(op.f('ix_repos_id'), table_name='repos')
    op.drop_index(op.f('ix_repos_cluster_id'), table_name='repos')
    op.drop_table('repos')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
