"""add_last_updated_at_to_alerts

Revision ID: 241e9fe3ed96
Revises: 1951c5a1ffce
Create Date: 2026-07-09 11:22:23.605702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241e9fe3ed96'
down_revision: Union[str, Sequence[str], None] = '1951c5a1ffce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_alerts_last_updated_at'), 'alerts', ['last_updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_last_updated_at'), table_name='alerts')
    op.drop_column('alerts', 'last_updated_at')
    # ### end Alembic commands ###
