"""
Alert Model
Generated by the automation engine in response to events.
Represents actionable notifications for the operations team.
"""

import uuid
from datetime import datetime
from typing import Optional
from sqlmodel import SQLModel, Field
from sqlalchemy import Column, String


class Alert(SQLModel, table=True):
    __tablename__ = "alerts"

    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        primary_key=True,
        index=True,
    )
    workspace_id: str = Field(foreign_key="workspaces.id", index=True)
    title: str = Field(max_length=255)
    message: str = Field(max_length=2000)
    severity: str = Field(
        sa_column=Column(String, nullable=False, index=True)
    )  # low | medium | high | critical
    category: str = Field(default="system")  # security | ci | performance | system
    repo_id: str = Field(foreign_key="repos.id", index=True)
    event_id: Optional[str] = Field(default=None, foreign_key="events.id")

    # State
    resolved: bool = Field(default=False, index=True)
    resolved_at: Optional[datetime] = Field(default=None)
    acknowledged: bool = Field(default=False)

    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    last_updated_at: Optional[datetime] = Field(default=None, index=True)
